### PR TITLE
TypeScript

### PR DESCRIPTION
**Pull request by drauggres**
Done:
 - [x] Compile CoffeeScript to JavaScript (drop *.coffee)
 - [x] Rewite JavaScript in TypeScript (drop *.js)
 - [x] Annotate with types as much as possible
 - [x] Add eslint, prettier

Lost:
- grunt (I think we don't really need it)
- grunt-jsonlint (package.json is linted by npm on any update)
- watch

For compatibility file names are not changed and the code is placed in `lib`.
Don't have any API changes from the current version.

refs https://github.com/openstf/adbkit/issues/48

### CODE REVIEW

**Comment by koral--** [comment]
@drauggres your PR does not pass DCO check. Please add sign off to your commits.

**Comment by drauggres** [comment]
> @drauggres your PR does not pass DCO check. Please add sign off to your commits.

Done.

There is one more issue I found: generated typescript declarations have a reference to `'@devicefarmer/adbkit-logcat'` which has no type declarations. So if you'll try to use this updated library from typescript you may get an error (until you write declarations for adbkit-logcat)

**Comment by koral--** [comment]
What do you suggest for that issue? Also rewriting `adbkit-logcat`?

**Comment by drauggres** [comment]
Should be enough to write declarations and include them into `adbkit-logcat` (or publish as `@types/adbkit-logcat`).
Rewriting will also do fine. BTW it will be not so hard, because it is already in es6. I can do it if you are interested.

P.S. obviously this problem does not affect anyone using this library from js.

**Comment by drauggres** [comment]
As another option we could replace `Logcat` to `any` here 

```typescript
client.openLogcat(serial: string, options?: {
        clear?: boolean;
    } | typeof callback, callback?: Callback<Logcat>): Bluebird<Logcat>;
```
It does reduce usefulness but can be done right now.

**Comment by koral--** [comment]
IMO the best option is to rewrite `adbkit-logcat` as well. Don't hesitate to do that.
That way no functionality is lost and no workarounds are needed.

**Review by koral-- — APPROVED** [review]

**Pull request merged**
