### PR TITLE
adbKit V3 ?

### PR DESCRIPTION
**Pull request by UrielCh**
Hi,

I made some major change to this project the main changes are:

* enforce Typescript.
* remove old babel code.
* upgrade to modern code style.
* drop callback support.
* split client.ts in client.ts and Deviceclient.ts.
* a lot more changes to make Typescript happy.

Changes are still in progress.

TODO:
- allow reusing adb shell connection to send multiple command.

### CODE REVIEW

**Comment by koral--** [comment]
Good to hear, let me know if PR will be ready for review!
Don't forget to add a sign-off in order for DCO to pass.
You may use a draft PR feature until it is WIP.

**Comment by UrielCh** [comment]
Hi,
All my Commit are now signed, and I rollback tab size from 4 to 2 space, and update eslint.

For my usage, I do not have any issue with this version.

maybe you could test it.

**Comment by koral--** [comment]
@UrielCh there are conflicts, could you resolve them please?

**Comment by UrielCh** [comment]
the getpackages changes has been integrated in my fork for a while.

please, consider testing my fork.

**Comment by drauggres** [comment]
@UrielCh This is not how things work in open source. In order to get this reviewed (not even speaking about get merged):
- you MUST fix these conflicts.
- you should keep original indentation (tabs, not spaces), at the moment it is impossible to review your changes.
- you must remove last two commits from this branch (they are not appropiate here)

Also it would be nice of you, to get your commits in order: squash/fixup them yourself in a reasonable way: nobody wants bunch of meaningless "updatedeps/clean" commits.

P.S. With all respect for your work.
P.P.S. I'm not in authority here, just care about the project.

**Comment by UrielCh** [comment]
It's impossible to check my changes as a simple merge. There is too much changes:

100% of file changes.
50% fonction call signature changes.
The main class had been split in 2.
I removed all callback, to keep only Promises I need the maintainer acceptation for the change.

For code formating, my visual studio code had conflict beetween .prettierrc and .eslintrc. I was thinking that I roll back my code formating to the original one, but it's look's not...
The formating was 2 spaces, 4 spaces, or 1 tab ?

The 2 lasts commit having 0 matching line with my fork.

I already use this code in my current project.

I still have 2 pending changes including removing the old doc, to use a generated one.

It's mostly time to speek.

**Comment by UrielCh** [comment]
Creating a new PR from a new Branch.

**Pull request closed without merging**
